language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - "RAILS_VERSION=3.2.13"
  - "RAILS_VERSION=3.1.12"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"
matrix:
  allow_failures:
    - env: "RAILS_VERSION=4.0.0"
    - env: "RAILS_VERSION=master"
  exclude:
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.0.20"
    - rvm: 2.0.0
      env: "RAILS_VERSION=3.1.12"
